[package]
name = "bilibili-webhook"
version = "0.1.0"
authors = ["LJason <ljason@ljason.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
panic = "abort"

[dependencies]
config = "0.10"
log = "0.4"
log4rs = "1.0"
reqwest = { version = "0.11", features = ["blocking"] }
rusqlite = "0.24"
serde = { version = "1.0", features = ["derive"] }
serde-xml-rs = "0.4"
threadpool = "1.8"
